### ISSUE TITLE
Constants can't depend on globals

### ISSUE THREAD

**Issue by glguy** [GaloisInc/saw-script#2622]
Constants need to be able to assume that globals are allocated.

I believe that we either need to stop assuming that constants can always be allocated or start assuming that globals are always allocated.

This statement is filtering out non-constant globals just before it tries to initialize *all* constants.

https://github.com/GaloisInc/saw-script/blob/master/saw-central/src/SAWCentral/Crucible/LLVM/Builtins.hs#L1762-L1763

 Here's an example.

`example.c`

```c
char gstuff[] = "stuff";
char* const p = &gstuff[2];
void noop() {}
```

```
clang -c example.c -emit-llvm
```

`example.saw`

```
m <- llvm_load_module "example.bc";
llvm_verify m "noop" [] false (llvm_execute_func []) rme;
```

```
AssertionFailure :1:0: error: in _start
Global symbol not allocated
Details:
  Global symbol "gstuff" has no associated allocation
```

**Comment by RyanGlScott** [comment]
The reason that SAW uses `initializeMemoryConstGlobals` to only populate immutable globals is an attempt to avoid a potential source of unsoundness when verifying functions that use mutable global variables. This potential source of unsoundness is described in more detail [here](https://galoisinc.github.io/saw-script/master/saw-user-manual/specification-based-verification.html#compositional-verification-and-mutable-allocations), but to summarize, SAW's solution to prevent this unsoundness requires that users explicitly allocate (using `llvm_alloc_global`) and initialize (using `llvm_points_to`) mutable globals when verifying a function.

As part of the current implementation of this part of SAW, it simply does not allocate or initialize any mutable globals at all upon loading the LLVM module, instead deferring these steps until SAW interprets the LLVM spec during verification. This has an unfortunate interaction with translating constants, however, which is something that happens during module loading. Because SAW does not allocate mutable globals when translating the module, the constant translation crashes when it encounters a mutable global that has not yet been allocated (e.g., the mutable global `gstuff`, used in the definition of the `p` constant in the program above).

#2623 proposes to fix this by always allocating mutable globals upon loading the LLVM module. I am reluctant to do this, as it means that users would no longer be required to write `llvm_alloc_global` in their specs. That, in turn, makes it much harder to tell which mutable globals are actually involved in the specification of a function—if everything is allocated, then potentially any mutable global could be written to. That makes certain static checks that SAW performs much harder, such as the check it performs to see if there are any underspecified mutable global variables in the postconditions of a compositional override.

Talking with @glguy about this some more, there is a potential middle ground: allocate and populate all global variables for the sake of translating constants (so that translating `p` would succeed), but when verifying a function in isolation, assume that each mutable global variable cannot be written to unless declared using `llvm_alloc_global`, and assume that each mutable global variable cannot be read from unless declared using `llvm_points_to`. This would achieve the best of both worlds.

**Comment by glguy** [comment]
A simpler solution would be to add a toggle to always allocate all globals. Verifications of files that don't have constants that depend on allocated globals would continue to be more convenient to verify, and ones that do have them would just need to be more explicit about maintaining global variable state, but they'd still be sound.

Doing this would probably be a much smaller change that trying to adapt the compositional verification logic to try and prevent people from assigning globals that weren't mentioned in an `llvm_alloc_global`

**Comment by RyanGlScott** [comment]
That would work, I suppose, although it's a fairly crude solution. Perhaps we should hide this behind an experimental `enable_*` feature so that only power users reach for it (similar to `enable_lax_loads_and_stores`)?

**Comment by glguy** [comment]
I updated the PR to make this a configurable, experimental knob.

To do something fancier we'd need to be quite certain that someone couldn't get backdoor access to a global that we were pretending wasn't available via a constant that took its address. I don't really have time to be fancy and I don't want to implement something unsound in a rush

**Comment by sauclovian-g** [comment]
I finally figured out what I don't like about that check: it's papering over an internal bug, which is that the spec with no assertion in the postcondition is interpreted differently in different contexts: verification treats the value as unspecified but overrides treat it as unchanged.

I think if we fixed that such that you can't write to anything that doesn't have a value bound in the postcondition, it would also eliminate this problem: the code under verification wouldn't be able to write to a global unless all of the stuff needed to assert a postcondition value appeared in the spec. However, that's even fancier :-|

**Comment by sauclovian-g** [comment]
ISTM if you need an immediate fix, do the quick thing, mark it experimental, and note in its documentation/help text that it's an ad hoc solution to a specific problem. Leave this issue open and we'll get it fixed properly later; the cost of that is that probably having to adjust your stuff later too.

**Comment by RyanGlScott** [comment]
> I finally figured out what I don't like about that check: it's papering over an internal bug, which is that the spec with no assertion in the postcondition is interpreted differently in different contexts: verification treats the value as unspecified but overrides treat it as unchanged.

That is true, but I think ultimately not relevant to doing a proper fix. Even if SAW required all specifications that allocate mutable globals in their preconditions to specify the values of those globals in their postconditions, we'd still have the problem that a user could do something like this:

```c
int mutable_global = 0;

int foo(void) {
  mutable_global = 1;
  return mutable_global;
}
```
```
let foo_spec = do {
  llvm_execute_func [];
  llvm_return (llvm_term {{ 1 : [32] }});
}
```

We want to reject `foo_spec` because it writes to (and reads from) `mutable_global` without ever allocating it. `foo_spec` would still pass the check describe above since it doesn't allocate any mutable globals at all in its postconditions, however. We'd need to do something else in order to reject `foo_spec` properly.

**Comment by sauclovian-g** [comment]
My intent was that this `foo_spec` would not pass, because the underlying code writes to the mutable global and the spec doesn't give it a postcondition value. It also reads from a global without allocating it, which shouldn't really be allowed either.

**Comment by RyanGlScott** [comment]
To clarify, today's SAW does reject `foo_spec`. I bring this up because it is a program that SAW _would_ accept if a user turns on `enable_alloc_all_globals`. I'd consider it to be a different class of program than the one than the check described [here](https://galoisinc.github.io/saw-script/master/saw-user-manual/specification-based-verification.html#compositional-verification-and-mutable-allocations) in the SAW manual is meant to catch. Your proposal of rejecting any specification that doesn't specify postcondition values for all mutable globals allocated in the precondition would cover programs like the ones described in that part of the SAW manual, but not programs like in `foo_spec`.

**Comment by sauclovian-g** [comment]
My proposal was to reject any specification that doesn't specify postcondition values for all mutable globals _written to by the code_. And, implicitly, also reject any specification that doesn't set up (in the precondition) all globals _read by the code_.

There are disadvantages to that, like not being able to paper over library internals. But I kind of feel like we shouldn't allow that anyway. And anything that reads a mutable global should be establishing or referring to its proper invariant, not assuming the initialization state, also as a matter of soundness. (That's #357 and #916.)

Anyway, I think it makes it safe to process all global initializers properly.

**Comment by kquick** [comment]
The merged #2623 provides for one way to address this issue.  Should this issue be closed pending any further refinement or would we like to keep this open to capture the conversation de jour?

**Comment by RyanGlScott** [comment]
I ultimately see #2623 as papering around the underlying issues presented here. I think we should keep this issue open as a reminder to revisit SAW's current design to see if there is a way to permit this in a way that is both sound and ergonomic.

**Comment by sauclovian-g** [comment]
Ultimately we need to fix the problem where we interpret the same spec differently in different contexts. After that, which is not trivial at all, the rest becomes easy...
